services:
  postgres:
    image: postgres:18-alpine
    container_name: fellahconnect-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: